version: "3.8"
services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - node-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=task-manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/models/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql # creates database's tables.
      - ./src/models/functions.sql:/docker-entrypoint-initdb.d/functions.sql # creates database's functions.

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    networks:
      - node-network
    depends_on:
      - database

networks:
  node-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data
    driver: local
